name: Compatibility Verification

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify plugin
        run: ./gradlew verifyPlugin

      - name: Upload Plugin Verifier Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: plugin-verifier-report
          path: build/reports/pluginVerifier